set(TESTS_SOURCES ${TESTS_SOURCES}
    AllpassCubicTest.cpp
    AllpassLinearTest.cpp
    AllpassStaticTest.cpp
    BufferTest.cpp
    DelayCubicTest.cpp
    DelayLinearTest.cpp
    DelayStaticTest.cpp
    HighpassFirstOrderTest.cpp
    HannOscillatorTest.cpp
    LowpassFirstOrderTest.cpp
    LowshelfFirstOrderTest.cpp
    ReaderCubicTest.cpp
    ReaderLinearTest.cpp
    ReaderTest.cpp
    SineOscillatorTest.cpp
    StaticPoolTest.cpp
    StaticAllocatorTest.cpp
    UnitTest.cpp
    WhiteNoiseTest.cpp
    WriterTest.cpp
    utilityTest.cpp
)
