set(MD_AUDIO_SOURCES ${MD_AUDIO_SOURCES}
    Allpass.cpp
    AllpassCubic.cpp
    AllpassLinear.cpp
    Buffer.cpp
    Delay.cpp
    DelayCubic.cpp
    DelayLinear.cpp
    HannOscillator.cpp
    Highpass.cpp
    Highshelf.cpp
    Impulse.cpp
    Latch.cpp
    Lowpass.cpp
    Lowshelf.cpp
    OnePole.cpp
    Oscillator.cpp
    Phasor.cpp
    Reader.cpp
    ReaderCubic.cpp
    ReaderLinear.cpp
    Shelving.cpp
    SineOscillator.cpp
    SineShaper.cpp
    Taus88.cpp
    WhiteNoise.cpp
    Writer.cpp
    Zdf.cpp
)
