set(MD_AUDIO_SOURCES ${MD_AUDIO_SOURCES}
    AllpassFirstOrder.cpp
    AllpassSecondOrder.cpp
    Bandpass.cpp
    Bandshelf.cpp
    Bandstop.cpp
    HannOscillator.cpp
    HighpassFirstOrder.cpp
    HighpassSecondOrder.cpp
    HighshelfFirstOrder.cpp
    HighshelfSecondOrder.cpp
    LowpassFirstOrder.cpp
    LowpassSecondOrder.cpp
    LowshelfFirstOrder.cpp
    LowshelfSecondOrder.cpp
    Oscillator.cpp
    Phasor.cpp
    SineOscillator.cpp
    Svf.cpp
    TiltFirstOrder.cpp
    TiltSecondOrder.cpp
    TptFirstOrder.cpp
    TptSecondOrder.cpp
    TptShelvingFirstOrder.cpp
    TptShelvingSecondOrder.cpp
    Unit.cpp
    WhiteNoise.cpp
)
